### PR TITLE
Add Replicate demo and API

### PR DESCRIPTION
**Pull request by chenxwh**
Hi @soujanyaporia,

Great work on another Tango model !!

This PR is the Replicate version of the `TangoFlux` (https://replicate.com/chenxwh/tangoflux). Happy to transfer the demo page to `declare-lab` as before :)

### CODE REVIEW

**Comment by soujanyaporia** [comment]
Wow! that was fast. Thanks so much! Are the APIs available as well?

**Comment by chenxwh** [comment]
> Wow! that was fast. Thanks so much! Are the APIs available as well?

Yes! API is automatically enabled for all demos :) https://replicate.com/chenxwh/tangoflux/api

**Comment by soujanyaporia** [comment]
Thanks! it would be great if you could transfer it to declare-lab. My university will need some API access for a demo. Is it possible to get it? Please feel free to send me an email when you get time. Thank you!

**Comment by chenxwh** [comment]
Sure thing, the demo is now here https://replicate.com/declare-lab/tangoflux, I also sent you an email regarding the credit for API access :)

**Pull request merged**
